from a5_part2_300129609 import Rectangle
from a5_part2_300129609 import Point
from a5_part2_300129609 import Canvas
r1=Rectangle(Point(),Point(1,1),'red')
print('Color of r1:',r1.get_color())
print('Bottom left point of r1',r1.get_bottom_left())
print('Top right point of r1',r1.get_top_right())
r1.reset_color("blue")
print('New color of r1:',r1.get_color())
print(r1)
'''r2 = eval(repr(r1))
print (r2)
print (r1 is r2)
print (r1==r2)'''
r3=Rectangle(Point(), Point(2,1), "red")
print('Perimeter of r3:',r3.get_perimeter())
r4=Rectangle(Point(1,1), Point(2,2.5), "blue")
print('Area of r1:',r4.get_area())
r5=Rectangle(Point(1,1), Point(2,2.5), "blue")
print('r4 == r5:',r4 == r5)
print('r4 is r5:',r4 is r5)
r=Rectangle(Point(1,1), Point(2,5), "blue")
print('r cointains Point(1.5,1):',r.contains(1.5,1))
print('r cointains Point(2,2):',r.contains(2,2))
print('r cointains Point(0,0):',r.contains(0,0))

print('\nNext Testing Section\n')

r1=Rectangle(Point(1,1), Point(2,2), "blue")
r2=Rectangle(Point(2,2.5), Point(3,3), "blue")
r3=Rectangle(Point(1.5,0),Point(1.7,3),"red")

print(r3)

print('r1 intersects r2:',r1.intersects(r2))
print('r2 intersects r1:',r2.intersects(r1))
print('r1 intersects r3:',r1.intersects(r3))
print('r2 intersects r3:',r2.intersects(r3))

print('\nNext Testing Section\n')

c=Canvas()
print('Length of canvas',len(c))

r1=Rectangle(Point(1,1), Point(2,2), "blue")
r2=Rectangle(Point(2,2.5), Point(3,3), "blue")
r3=Rectangle(Point(1.5,0),Point(1.7,3),"red")
c.add_one_rectangle(r1)
c.add_one_rectangle(r2)
c.add_one_rectangle(r3)
c.add_one_rectangle( Rectangle(Point(0,0),Point(100,100),"orange") )
print('Length of canvas',len(c))
print('Canvas c:',c)
print('Number of blue rectangle in c',c.count_same_color('blue'))
print('Number of red rectangle in c',c.count_same_color('red'))
print('Number of purple rectangle in c',c.count_same_color('purple'))

print('\nNext Testing Section\n')

c=Canvas()
r1=Rectangle(Point(1,1), Point(2,2), "blue")
r2=Rectangle(Point(1,1), Point(4,4), "blue")
r3=Rectangle(Point(-2,-2), Point(-1,-1), "blue")
c.add_one_rectangle(r1)
c.add_one_rectangle(r2)
c.add_one_rectangle(r3)
print('Total perimeter of canvas c',c.total_perimeter())

print('\nNext Testing Section\n')

c=Canvas()
r1=Rectangle(Point(1,1), Point(2,2), "blue")
r2=Rectangle(Point(1,1), Point(4,4), "blue")
r3=Rectangle(Point(-2,-2), Point(-1,-1), "blue")
r4=Rectangle(Point(0,-100),Point(1,100), "yellow")
c.add_one_rectangle(r1)
c.add_one_rectangle(r2)
c.add_one_rectangle(r3)
c.add_one_rectangle(r4)
print(c.min_enclosing_rectangle())

print('\nNext Testing Section\n')

c=Canvas()
r1=Rectangle(Point(1,1), Point(2,2), "blue")
r2=Rectangle(Point(1.5,1.5), Point(4,4), "blue")
r3=Rectangle(Point(-2,-2), Point(2,1.5), "blue")
r4=Rectangle(Point(0,-100),Point(1.5,100), "yellow")
c.add_one_rectangle(r1)
c.add_one_rectangle(r2)
c.add_one_rectangle(r3)
c.add_one_rectangle(r4)
print('Common point on canvas c:',c.common_point())

print('\nNext Testing Section\n')

c=Canvas()
r1=Rectangle(Point(-2,-2), Point(-1,2), "blue")
r2=Rectangle(Point(-2,-2), Point(2,-1), "blue")
r3=Rectangle(Point(1,-2), Point(2,2), "blue")
r4=Rectangle(Point(-2,1), Point(2,2), "blue")
c.add_one_rectangle(r1)
c.add_one_rectangle(r2)
c.add_one_rectangle(r3)
c.add_one_rectangle(r4)
print('Common point on canvas c:',c.common_point())
